<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
<xsl:output method="xml" indent="yes" />

<xsl:template match="month">

<html lang="en">

  <head>
    <title><xsl:value-of select="summary/title"/><xsl:text> </xsl:text><xsl:value-of select="summary/year"/> planner | generated by Polyrex-Calendar</title>
    <link rel="stylesheet" href="month_layout.css"/>
    <link rel="stylesheet" href="month.css"/>
  </head>

  <body>
    <div id="wrap">
  <h1><xsl:value-of select="summary/title"/><xsl:text> </xsl:text><xsl:value-of select="summary/year"/></h1>
  <table border="1">
    <tr><th>Sunday</th><th>Monday</th><th>Tuesday</th><th>Wednesday</th><th>Thursday</th><th>Friday</th><th>Saturday</th></tr>
      <xsl:apply-templates select="records"/>
  </table>
    </div>
  </body>
</html>

</xsl:template>

<xsl:template match="month/summary">
  <caption><xsl:value-of select="title"/></caption>
</xsl:template>


<xsl:template match="records/week">
  <tr>
  <xsl:apply-templates select="summary"/>
  <xsl:apply-templates select="records"/>
  </tr>
</xsl:template>

<xsl:template match="week/summary">

</xsl:template>

<xsl:template match="records/day">
  <xsl:apply-templates select="summary"/>
</xsl:template>

<xsl:template match="day/summary">
  <xsl:element name="td">
    <xsl:if test="css_style">
      <xsl:attribute name="class"><xsl:value-of select="css_style"/></xsl:attribute>
    </xsl:if>
    <div>
      <xsl:if test="title!=''">
        <xsl:value-of select="xday"/>
      </xsl:if>
    </div>

      <div><xsl:value-of select="bankholiday"/></div>
      <div><xsl:value-of select="event"/></div>

  </xsl:element>
</xsl:template>


</xsl:stylesheet>